export const SET_DEFAULT_CATEGORY_ID = 'SET_DEFAULT_CATEGORY_ID';
export const SET_DEFAULT_CATEGORY_ID_ERROR = 'SET_DEFAULT_CATEGORY_ID_ERROR';
export const SET_DEFAULT_CATEGORY_ID_PENDING_STATUS =
  'SET_DEFAULT_CATEGORY_ID_PENDING_STATUS';
export const RESET_DEFAULT_CATEGORY_ID_PENDING_STATUS =
  'RESET_DEFAULT_CATEGORY_ID_PENDING_STATUS';
