export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_CATEGORIES_GET_ERROR = 'SET_CATEGORIES_GET_ERROR';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const SET_CATEGORY_CREATE_REQUEST = 'SET_CATEGORY_CREATE_REQUEST';
export const SET_CATEGORY_CREATE_ERROR = 'SET_CATEGORY_CREATE_ERROR';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const SET_CATEGORY_PENDING_STATUS = 'SET_CATEGORY_PENDING_STATUS';
export const RESET_CATEGORY_PENDING_STATUS = 'RESET_CATEGORY_PENDING_STATUS';
