export const SET_TASKS = 'SET_TASKS';
export const ADD_TASK = 'ADD_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const DELETE_TASK = 'DELETE_TASK';
// export const SET_TASKS_GET_REQUEST = 'SET_TASKS_GET_REQUEST';
export const SET_TASKS_GET_ERROR = 'SET_TASKS_GET_ERROR';
export const SET_TASKS_CREATE_REQUEST = 'SET_TASKS_CREATE_REQUEST';
export const SET_TASKS_CREATE_ERROR = 'SET_TASKS_CREATE_ERROR';
export const SET_TASKS_MODIFY_START = 'SET_TASKS_MODIFY_START';
export const SET_TASKS_MODIFY_FINISH = 'SET_TASKS_MODIFY_FINISH';
export const SET_TASKS_RESOLVED_SORT_STATE = 'SET_TASKS_RESOLVED_SORT_STATE';

export const SET_TASKS_SORT_REQUEST = 'SET_TASKS_SORT_REQUEST';
// export const SET_TASKS_SORT_ERROR = 'SET_TASKS_SORT_ERROR';
